services:
  oracle-db:
    image: gvenzl/oracle-free:23.3-slim-faststart
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - ORACLE_DATABASE=MOOPPDB1
      - APP_USER=${APP_USER}
      - APP_USER_PASSWORD=${APP_USER_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - ./db/init:/container-entrypoint-initdb.d
    networks: [shared_net]


  backend:
    build: ./backend
    container_name: backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_SSL_ENABLED=${REDIS_SSL_ENABLED}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - COGNITO_DOMAIN=${COGNITO_DOMAIN}
      - REDIRECT_URI=${REDIRECT_URI}
      - spring.profiles.active=local
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    networks: [shared_net]

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: [shared_net]

volumes:
  redis-data:

networks:
  shared_net:
    name: shared_net
    driver: bridge
