apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hiroshiimaizumi0611/java_springboot_backend.git
    targetRevision: main
    path: backend/helm-chart
    helm:
      valueFiles: [ values.yaml, values-prod.yaml ]
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [ "CreateNamespace=true" ]
