server:
    port: 8080
    error:
        whitelabel:
            enabled: false
    forward-headers-strategy: framework

spring:
    application:
        name: estimate-api
    session:
        store-type: redis
    security:
        oauth2:
            client:
                registration:
                    cognito:
                        client-id: ${CLIENT_ID}
                        client-secret: ${CLIENT_SECRET}
                        scope: openid, email, profile
                        authorization-grant-type: authorization_code
                        redirect-uri: ${REDIRECT_URI}
                        provider: cognito
                provider:
                    cognito:
                        issuerUri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_WKRebkGWn
                        user-name-attribute: email
    datasource:
        url: jdbc:oracle:thin:@//${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
        hikari:
            connection-init-sql: ALTER SESSION SET CURRENT_SCHEMA=APP_OWNER
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            username: ${REDIS_USERNAME}
            password: ${REDIS_PASSWORD}
            ssl: 
                enabled: ${REDIS_SSL_ENABLED}

jwt:
  secret: ${JWT_SECRET}

app:
  idp:
    registration-id: cognito
  session:
    idle-timeout-minutes: 120
  csv:
    bucket-name: estimate-app-csv-files
    url-expiry-minutes: 10
