server:
    port: 8080
    error:
        whitelabel:
            enabled: false
    forward-headers-strategy: framework
    shutdown: graceful

spring:
    application:
        name: estimate-api
    session:
        store-type: redis
        redis:
            # Use a constant hash-tagged namespace so Redis Cluster keeps session keys in the same slot
            # to avoid CROSSSLOT on RENAME during session id changes.
            namespace: spring:session:{backend}
    lifecycle:
        timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}
    datasource:
        url: jdbc:oracle:thin:@//${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
        hikari:
            connection-init-sql: ALTER SESSION SET CURRENT_SCHEMA=APP_OWNER
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            username: ${REDIS_USERNAME}
            password: ${REDIS_PASSWORD}
            ssl: 
                enabled: ${REDIS_SSL_ENABLED}
    task:
        execution:
            shutdown:
                await-termination: true
                await-termination-period: ${TASK_EXEC_SHUTDOWN:30s}
        scheduling:
            shutdown:
                await-termination: true
                await-termination-period: ${TASK_SCHED_SHUTDOWN:30s}

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            probes:
                enabled: true

jwt:
  secret: ${JWT_SECRET}

app:
  idp:
    registration-id: cognito
  jwt:
    at-ttl-minutes: 10
  session:
    idle-timeout-minutes: 120
  csv:
    bucket-name: estimate-app-csv-files
    url-expiry-minutes: 10
  log:
    level: INFO
  web:
    redirect-url: /
