spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            provider: azure
        provider:
          azure:
            # Entra ID (Azure AD) issuer. 例: https://login.microsoftonline.com/{tenantId}/v2.0
            issuer-uri: ${AZURE_ISSUER_URI}

app:
  idp:
    registration-id: azure
  log:
    level: INFO
