spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid, email, profile
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            provider: cognito
        provider:
          cognito:
            issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_WKRebkGWn
            user-name-attribute: email

app:
  idp:
    registration-id: cognito
  log:
    level: DEBUG
