replicaCount: 2

image:
  repository: 635566485987.dkr.ecr.ap-northeast-1.amazonaws.com/springboot-api
  tag: 49988aa
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

# Non-secret environment variables passed to the Pod
# Override per environment: e.g. --set env.SPRING_PROFILES_ACTIVE=prod
env:
  SPRING_PROFILES_ACTIVE: prod
